### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by aliou** [aliou/dotvim#4]
##### Todo
- [ ] ~~Use an env variable to access the nvim configuration path~~
- [x] ~~Find a way to load plugins from a file local to a folder e.g. `.vimrc.local`~~
- [x] Drop jdaddy to only use `:%!jq '.'` with [`jq`](https://stedolan.github.io/jq/)
- [ ] Add a variable or a command to directly navigate to the `~/code/src` folder

##### Bugs
- [ ] Interesting words not working. (neovim ?)
- [x] ctrlp not working sometimes (=> only the matcher, neovim issue)

##### Later
- [ ] Fuzzy jump to tag ?
